# Generated by Django 3.1.5 on 2021-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('1', 'Province No. 1'), ('2', 'Province No. 2'), ('3', 'Bagmati Province'), ('4', 'Gandaki Province'), ('5', 'Lumbani Province'), ('6', 'Karnali Province'), ('7', 'Sudurpashchim Province')], max_length=100),
        ),
    ]
